[general]
library_name = "libawscrt"
smart_de_anonymize = true
extract_c_comment_style = "doxygen"
show_c_function_prototype = true
output_ignorelist = [
    "AWS_RESTRICT",
    "AWS_THREAD_LOCAL",
    "SIZE_MAX_POWER_OF_TWO",
    "AWS_COMMON_MATH_API",
    "AWS_THREAD_ONCE_STATIC_INIT",
    "AWS_BUS_ADDRESS_ALL",
]

auto_mutability = false
auto_mutability_with_new = false
auto_mutability_includelist = ["aws_socket_options", "aws_tls_connection_options"]

[codegen]
use_julia_bool = true
